name: Generate Powered-By
on:
  push:
#    branches:
#      - main

jobs:
  generate-powered-by:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install node 
      uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org

    - name: Install license-report and jq
      run: |
        sudo apt-get update -y && sudo apt-get install -y jq
        sudo npm install -g license-report

    - name: Install project dependencies
      run: |
        npm ci

    - name: Generate Powered-By
      run: |
        ./generate_power-by.sh

    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Generate powered-by"
        file_pattern: "powered-by.md"
